[Entry] ClickSpeed
reactph/rehackt-challenge-week-one pull request #15
Opened 2021-10-18 17:00 UTC by aindong

Adjust the volume base on the Click / Second

2021-10-19 09:30 UTC, fransaycon requested changes
thanks for the entry. just a few comments. :D

2021-10-19 09:30 UTC, fransaycon commented on src/entries/ClickSpeed/ClickSpeed.jsx
> +    console.log("Volume", clicksPerS * 10)
remove the consoles bro :D

2021-10-19 09:30 UTC, fransaycon commented on src/entries/ClickSpeed/ClickSpeed.jsx
> +    console.log("End Time", newEndTime)
stray console.

2021-10-19 19:46 UTC, aindong commented
Thank you @franreysaycon! I totally forgot about my consoles! 😅

2021-10-20 10:25 UTC, fransaycon approved these changes

2021-10-20 10:25 UTC, merged