Create TextTypingGame
reactph/rehackt-challenge-week-one pull request #16
Opened 2021-10-26 03:07 UTC by briankarlsayen

new entry Text Typing Game

2021-10-26 13:42 UTC, galacemiguel commented
Hi, @briankarlsayen! It looks like there are some formatting issues with your entry. 🧐

Can you run the following and push again? Thanks!

```
yarn prettier --write src/entries/TextTypingGame
```

2021-10-27 00:22 UTC, briankarlsayen commented
> Hi, @briankarlsayen! It looks like there are some formatting issues with your entry. 🧐
> 
> Can you run the following and push again? Thanks!
> 
> ```
> yarn prettier --write src/entries/TextTypingGame
> ```

ok na boss

2021-10-27 02:17 UTC, galacemiguel requested changes
One last thing! Pa-undo na lang ng changes mo doon sa `package.json` at `yarn.lock`. 'Di na dapat siya kailangan. 😄

Ganda ng gawa mo though! Maybe my favorite entry so far.

2021-10-27 02:17 UTC, galacemiguel commented on package.json
> +    "rehackt-challenge-week-one": "https://github.com/briankarlsayen/rehackt-challenge-week-one.git",
```suggestion
```

2021-10-27 02:17 UTC, galacemiguel commented on yarn.lock
> +
```suggestion
```

2021-10-27 02:17 UTC, galacemiguel commented on yarn.lock
> +    watchpack-chokidar2 "^2.0.1"
```suggestion
    graceful-fs "^4.1.2"
    neo-async "^2.5.0"
```

2021-10-27 03:25 UTC, briankarlsayen commented
Sir pa check nlng po ulet kung may conflict pa. Thanks.

2021-10-27 11:06 UTC, galacemiguel commented on yarn.lock
> +    watchpack-chokidar2 "^2.0.1"
Ito na lang kulang, @briankarlsayen. 🙏

2021-10-27 12:01 UTC, briankarlsayen commented on yarn.lock
> +    watchpack-chokidar2 "^2.0.1"
yarn sir @galacemiguel ok na ata haha

2021-10-28 09:44 UTC, galacemiguel commented
> Sir pa check nlng po ulet kung may conflict pa. Thanks.

@briankarlsayen Sumobra ang na-delete mo sir. 😅

Dapat walang diff ang [`yarn.lock` sa **Files changed**](https://github.com/reactph/rehackt-challenge-week-one/pull/16/files#diff-51e4f558fae534656963876761c95b83b6ef5da5103c4adef6768219ed76c2de
):

![image](https://user-images.githubusercontent.com/7394331/139231078-cdc17e7c-df4f-4849-8a68-581426d897c7.png)

2021-10-28 10:09 UTC, briankarlsayen commented
@galacemiguel idedelete ko lng ung     

- graceful-fs "^4.1.2"
- neo-async "^2.5.0"

or 

    chokidar "^3.4.1"
    graceful-fs "^4.1.2"
    neo-async "^2.5.0"
    watchpack-chokidar2 "^2.0.1"

2021-10-29 10:10 UTC, galacemiguel approved these changes
Ito lang @briankarlsayen para mabalik sa dati yung `yarn.lock`. 😄 

```
git checkout main -- yarn.lock
```

Pinush ko na. Thanks for contributing and we hope to see you at our event later! ✨

2021-10-29 10:10 UTC, merged